JW-954 build cleanup
codilime/contrail-build pull request #7
Opened 2017-08-03 10:58 UTC by michal-clapinski

2017-08-03 16:14 UTC, katrybacka commented on rules.py
> +    subprocess.call("xxd -i " + hname + " >> " + os.path.basename(cname), shell = True, cwd = opath)
remove spaces before and after equal sign

2017-08-03 16:15 UTC, katrybacka commented on rules.py
> +    subprocess.call("cat " + tname + " >> " + cname, shell = True)
same here

2017-08-03 16:32 UTC, katrybacka requested changes

2017-08-03 16:32 UTC, katrybacka commented on rules.py
> +    return '%s -f -g ifmap-backend -o %s %s' % (os.path.join('.', 'tools', 'generateds', 'generateDS.py'), output, source[0])
better use `File(#tools/generateds/generateDS.py).abspath`

2017-08-03 16:32 UTC, katrybacka commented on rules.py
> +    subprocess.call("xxd -i " + hname + " >> " + os.path.basename(cname), shell = True, cwd = opath)
remove spaces before and after equal sign

2017-08-03 16:32 UTC, katrybacka commented on rules.py
> +    subprocess.call("cat " + tname + " >> " + cname, shell = True)
same here

2017-08-03 16:32 UTC, katrybacka commented on rules.py
> +    return '%s -f -g type -o %s %s' % (os.path.join('.', 'tools', 'generateds', 'generateDS.py'), output, source[0])
same here

2017-08-04 10:32 UTC, katrybacka approved these changes

2017-08-04 15:22 UTC, sodar approved these changes

2017-08-04 15:25 UTC, merged